name: Auto Update Pull Requests

on:
  push:
    branches:
      - main

jobs:
  autoupdate:
    runs-on: amd-standard
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_READY_STATE: ready_for_review

